[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "celery -A celery_worker.celery_app worker --loglevel=info --concurrency=2"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
